services:
  postgres:
    image: postgres:18-alpine
    container_name: task_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-taskdb}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-taskdb}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI to view emails
#
#  redis:
#    image: redis:8.6-alpine
#    container_name: task_redis
#    restart: unless-stopped
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis_data:/data
#    healthcheck:
#      test: ["CMD", "redis-cli", "ping"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 5s

  be:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: task_be
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      mailhog:
        condition: service_started
#      redis:
#        condition: service_healthy
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-taskdb}
      REDIS_URL: redis://redis:6379s
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret}
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"

volumes:
  postgres_data:
#  redis_data:

